# Generated by Django 3.2.9 on 2021-12-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='text',
            new_name='name',
        ),
    ]
