# Generated by Django 3.2.9 on 2021-12-03 15:41

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_text_userdetail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
