# Generated by Django 3.2.9 on 2021-12-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userdetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='age',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
