# Generated by Django 3.2.9 on 2021-12-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userdetail_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='age',
            field=models.IntegerField(max_length=50),
        ),
    ]
