# Generated by Django 3.2.9 on 2021-12-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211204_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='occupation',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
