# Generated by Django 3.2.9 on 2021-12-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_userdetail_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
